### ISSUE TITLE
poll dual posting results. 

### ISSUE THREAD

**Issue by MrDadShot** [ptoast/FlapJack-Cogs#127] opened 2021-02-21 09:42 UTC
Poll seems to post results after ending. If i end a poll a few days before scheduled it will still post results on scheduled date also.

**Comment by aikaterna** [comment] 2022-10-13 19:09
I believe this is a duplicate of #142 (or more accurately, #142 is a duplicate of this issue), but because that issue has more information I will track progress on it there. I will post a commit link on that issue when that is resolved.

**Closed as completed by aikaterna** 2022-10-13 19:09 UTC
