### ISSUE TITLE
gifs emojis still dosnt work for smart reaction also there is no Priority for reacting a msg

### ISSUE THREAD

**Issue by kpopdev** [ptoast/FlapJack-Cogs#100] opened 2019-08-13 06:29 UTC
gifs emojis still dosnt work for smart reaction also there is no Priority for reacting a msg

**Comment by aikaterna** [comment] 2019-08-24 20:51
I was able to add an animated emoji through the addreact command. Please make sure it is an emoji that the bot can see on one of the servers it's on.
What do you mean by "no priority for reacting a msg"?

**Comment by spAnser** [comment] 2019-09-14 20:51
Actually this was fixed in v3 of the cog not the v2 cog

**Comment by kpopdev** [comment] 2019-10-23 11:29
like when you add first 1 then 2 then 3 and 4 
it add like 4 2 1 3 emojis to a msg

**Comment by aikaterna** [comment] 2020-05-16 22:26
Closing as this is a duplicate of #44. Fixes addressing this will be tied to that issue.

**Closed as completed by aikaterna** 2020-05-16 22:26 UTC
Labels: V2
